spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: driver-service
          uri: lb://DRIVER-SERVICE
          predicates:
            - Path=/api/v1/drivers/**
          filters:
            - name: CircuitBreaker
              args:
                name: driver-service-circuit
                fallbackUri: redirect:/fallback/driver-service
        - id: driver-service-cars
          uri: lb://DRIVER-SERVICE
          predicates:
            - Path=/api/v1/cars/**
          filters:
            - name: CircuitBreaker
              args:
                name: driver-service-circuit
                fallbackUri: redirect:/fallback/driver-service
        - id: passenger-service
          uri: lb://PASSENGER-SERVICE
          predicates:
            - Path=/api/v1/passengers/**
          filters:
            - name: CircuitBreaker
              args:
                name: passenger-service-circuit
                fallbackUri: redirect:/fallback/passenger-service
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - name: CircuitBreaker
              args:
                name: payment-service-circuit
                fallbackUri: redirect:/fallback/payment-service
        - id: ride-service
          uri: lb://RIDE-SERVICE
          predicates:
            - Path=/api/v1/rides/**
          filters:
            - name: CircuitBreaker
              args:
                name: ride-service-circuit
                fallbackUri: redirect:/fallback/ride-service
        - id: eureka-server
          uri: http://eureka@discovery-server:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: eureka-server-static
          uri: http://eureka@discovery-server:8761
          predicates:
            - Path=/eureka/**
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus", "health" ]
    metrics:
      tags:
        application: ${spring.application.name}
    endpoint:
      health:
        show-details: always
      metrics:
        enabled: true
    health:
      circuitbreakers:
        enabled: true
    prometheus:
      metrics:
        export:
          enabled: true
