spring:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  datasource:
    url: ${MYSQL_JDBC_URL:jdbc:mysql://localhost:3306/cabDB?createDatabaseIfNotExist=true}
    username: ${MYSQL_USERNAME:user}
    password: ${MYSQL_PASSWORD:pass}
  application:
    name: DRIVER-SERVICE
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
    hibernate:
      ddl-auto: validate
    generate-ddl: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
server:
  port: 0