spring:
  messages:
    basename: validation
  datasource:
    url: jdbc:mysql://localhost:3306/cabDB?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: pass
  application:
    name: DRIVER-SERVICE
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
    hibernate:
      ddl-auto: validate
    generate-ddl: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json:
          trusted.packages: "*"
          type.mapping: RatingToDriverRequest:com.nikonenko.driverservice.dto.RatingToDriverRequest
      group-id: ride-group
      auto-offset-reset: latest
      rating-topic-name: driver-rating-topic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: ChangeRideStatusRequest:com.nikonenko.driverservice.dto.ChangeRideStatusRequest, ReviewRequest:com.nikonenko.driverservice.dto.ReviewRequest
      status-producer-topic:
        name: ride-status-topic
      driver-review-topic:
        name: driver-review-topic

eureka:
  client:
    service-url:
      defaultZone: http://eureka@localhost:8761/eureka/

server:
  port: 8082

feign:
  client:
    config:
      ride:
        name: RIDE-SERVICE
        path: /api/v1/rides

resilience4j:
  circuitbreaker:
    instances:
      rideBreaker:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 20
        waitDurationInOpenState: 50s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  retry:
    instances:
      rideRetry:
        maxAttempts: 3
        waitDuration: 10s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2