spring:
  messages:
    basename: validation
  data:
    mongodb:
      database: rides-db
      host: mongodb
      port: 27017
      authentication-database: admin
  application:
    name: RIDE-SERVICE
mongock:
  migration-scan-package:
    - com.nikonenko.rideservice.migrations
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
server:
  port: 0