spring:
  datasource:
    url: ${MYSQL_JDBC_URL:jdbc:mysql://mysqldb:3306/cabDB?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false}
    username: ${MYSQL_USERNAME:user}
    password: ${MYSQL_PASSWORD:pass}
  application:
    name: PASSENGER-SERVICE
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
    hibernate:
      ddl-auto: validate
    generate-ddl: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  kafka:
    producer:
      bootstrap-servers: broker:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: PassengerReviewRequest:com.nikonenko.passengerservice.dto.PassengerReviewRequest
      passenger-review-topic:
        name: passenger-review-topic

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
server:
  port: 0