spring:
  messages:
    basename: validation
  datasource:
    url: ${MYSQL_JDBC_URL:jdbc:mysql://mysqldb:3306/cabDB?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false}
    username: ${MYSQL_USERNAME:user}
    password: ${MYSQL_PASSWORD:pass}
  application:
    name: PASSENGER-SERVICE
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
    hibernate:
      ddl-auto: validate
    generate-ddl: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  kafka:
    consumer:
      bootstrap-servers: broker:29092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json:
          trusted.packages: "*"
          type.mapping: RatingToPassengerRequest:com.nikonenko.passengerservice.dto.RatingToPassengerRequest
      group-id: passenger-group
      auto-offset-reset: latest
      rating-topic-name: passenger-rating-topic
    producer:
      bootstrap-servers: broker:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: ReviewRequest:com.nikonenko.passengerservice.dto.ReviewRequest, CustomerCreationRequest:com.nikonenko.passengerservice.dto.CustomerCreationRequest
      passenger-review-topic:
        name: passenger-review-topic
      payment-customer-topic:
        name: payment-customer-topic

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
server:
  port: 0

feign:
  client:
    config:
      payment:
        name: PAYMENT-SERVICE
        path: /api/v1/payments
      ride:
        name: RIDE-SERVICE
        path: /api/v1/rides